title: Hugo Arellano
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-minimal
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "carellano1@ucol.mx"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
