title: 
  <h1 align="center">Hugo Arellano </h1>

logo: "/images/picture.png?raw=true"

description:  
  <p align="center">
  <a href="pdf/Hugo_Arellano.pdf">Resume</a> |
  <a href="https://github.com/economistanddatascientist">GitHub</a> |
  <a href="mailto:carloshugoarellano4@gmail.com">Email</a>
  </p>

  <p align="centre">
  Learner, economist, amateur coder and sportsman.  
  </p>

theme: jekyll-theme-minimal
