title: Hugo Arellano

avatar: "/images/picture.jpeg?raw=true"

round-avatar: true

description:  
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a>
  <a href="https://github.com/economistanddatascientist">GitHub</a>
  </p>

  <p align="justify">
  I am an economist in love of data science.
  </p>

theme: jekyll-theme-minimal
