title: <p align="center"> HUGO ARELLANO </p>

logo: "/images/picture.png?raw=true"

description:  
  <p align="center">
  <a href="pdf/Hugo_Arellano.pdf">Resume</a> |
  <a href="https://github.com/economistanddatascientist">GitHub</a> |
  <a href="mailto:carloshugoarellano4@gmail.com">Email</a>
  </p>

  <p align="justify">
  Learner, economist, sportsman and data scientist in progress.  
  <br><br>
  I have a bachelor's degree in economics from the University of Colima, to the final 
  semesters I fell in love with the structure, synthesis, and power that contains lines 
  of code for data analysis. Since this happend I been working a lot by myself for learn
  and applied this power in different projects. 
  <br><br>
  I'll hope that you find helpful.
  <br><br>
  Regarts, Hugo. 
  </p>

theme: jekyll-theme-minimal
