title: <p align="center"> HUGO ARELLANO </p>

logo: "/images/picture.png?raw=true"

description:  
  <p align="center">
  <a href="pdf/Hugo_Arellano.pdf">Resume</a> |
  <a href="https://github.com/economistanddatascientist">GitHub</a> |
  <a href="mailto:carloshugoarellano4@gmail.com">Email</a>
  </p>

  <p align="justify">
  Learner, economist, sportsman and data scientist in progress.  
  <br><br>
  I've working for almost 6 years in the public sector of economics, also I've 
  been the oportunity to work in several projects and develoment mines for fun.
  In this website you'll find some of them, be free and exploring.
  <br><br>
  Regarts,Hugo. 
  </p>

theme: jekyll-theme-minimal
