title: Hugo Arellano

description:  
  <p align="center">
  <a href="https://github.com/economistanddatascientist">GitHub</a>
  </p>

  <p align="justify">
  I am an economist in love of data science.
  </p>

theme: jekyll-theme-minimal
